name: Main Workflow

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get PR details
      run: |
        echo "PR_NO: ${{ github.event.pull_request.number }}"
      env:
        GH_TOKEN: ${{ github.token }}
