name: Main Workflow

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y

    - name: Get PR details
      id: get_pr_details
      run: |
        PR_NO=${{ github.event.pull_request.number }}
        PR_BODY=$(gh pr view $PR_NO)
        echo "PR_BODY: $PR_BODY"
        ORG_NAME=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*Org Name\*\*: \[).*(?=\])')
        USERNAME=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*Username\*\*: \[).*(?=\])')
        REPO_NAME=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*Repo Name\*\*: \[).*(?=\])')
        echo "ORG_NAME=$ORG_NAME" >> $GITHUB_ENV
        echo "USERNAME=$USERNAME" >> $GITHUB_ENV
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Validate user existence in org and repo
      id: validate
      run: |
        ORG=$ORG_NAME
        REPO=$REPO_NAME
        USER=$USERNAME

        echo "ORG: $ORG"
        echo "REPO: $REPO"
        echo "USER: $USER"
              
        # Check if user has owner permissions in the repository
        USER_PERMISSIONS=$(gh api repos/$ORG/$REPO/collaborators/$USER/permission --jq '.permission')
        if [ "$USER_PERMISSIONS" != "admin" ]; then
          echo "User $USER does not have owner permissions in the repository $REPO"
          exit 1
        fi   

        echo "Validation successful"
      env:
        GH_TOKEN: ${{ github.token }}

        echo "Validation successful"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Run Snyk scan
      uses: snyk/actions@master
      with:
        args: test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
